
All:example14

example14: example14.c 
	g++ -Wall -Wextra -g example14.c  -o example14 \
	-I /usr/local/include/opencv -I /usr/local/include  -L /usr/local/lib \
	-lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video \
	-lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib \
	-lopencv_legacy -lopencv_flann  

clean: 
	rm example14

